# Generated by Django 3.0.3 on 2020-02-18 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0002_homepage3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage3',
            new_name='hoursLocation',
        ),
    ]
