# Generated by Django 3.0.3 on 2020-02-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchvehicles',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='dealershiphours',
            name='body',
        ),
        migrations.RemoveField(
            model_name='dealershiphours',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dealershiphours',
            name='year',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='year',
        ),
        migrations.DeleteModel(
            name='HomePage2',
        ),
    ]
