# Generated by Django 3.0.3 on 2020-02-17 02:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=wagtail.core.fields.RichTextField(default='0', null=True),
        ),
    ]
