# Generated by Django 3.0.3 on 2020-02-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0002_auto_20200217_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
