# Generated by Django 3.0.3 on 2020-02-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0003_auto_20200217_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mpg',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
