# Generated by Django 3.0.3 on 2020-02-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0004_car_mpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_line',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='stock_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='mpg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
