# Generated by Django 3.0.3 on 2020-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0005_auto_20200217_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_line',
            field=models.CharField(default='2WD', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(default='5.3L V-6', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_color',
            field=models.CharField(default='black', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='mpg',
            field=models.CharField(default='22', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='stock_number',
            field=models.CharField(default='V220031', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='4-Speed auto', max_length=200),
        ),
    ]
