# Generated by Django 3.0.3 on 2020-02-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0010_auto_20200220_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('car', 'Car')], default='', max_length=200, null=True),
        ),
    ]
