# Generated by Django 3.0.3 on 2020-02-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0013_auto_20200220_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('1', 'Car'), ('2', 'Truck'), ('3', 'SUV'), ('4', 'Van')], default='1', max_length=200, null=True),
        ),
    ]
