# Generated by Django 3.0.3 on 2020-02-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0016_auto_20200220_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='carType',
            field=models.CharField(choices=[('1', 'Car'), ('2', 'Truck'), ('3', 'SUV'), ('4', 'Van')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
