# Generated by Django 3.0.3 on 2020-02-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0019_vehicle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.CharField(default='$', max_length=200, null=True),
        ),
    ]
