# Generated by Django 3.0.3 on 2020-02-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0020_auto_20200222_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
