# Generated by Django 3.0.3 on 2020-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0024_auto_20200226_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='carType',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Truck', 'Truck'), ('SUV', 'Suv'), ('Van', 'Van')], max_length=200, null=True),
        ),
    ]
