# Generated by Django 3.0.3 on 2020-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0027_auto_20200226_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
