# Generated by Django 3.0.3 on 2020-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0028_auto_20200302_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='', max_length=200),
        ),
    ]
