# Generated by Django 3.0.3 on 2020-03-09 21:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0029_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='testfield',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
