# Generated by Django 3.0.3 on 2020-03-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0030_vehicle_testfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
