# Generated by Django 3.0.3 on 2020-03-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0034_auto_20200310_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='testfield',
        ),
    ]
