# Generated by Django 3.0.3 on 2020-03-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('carlist', '0035_remove_vehicle_testfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='VehicleGallery',
        ),
    ]
