# Generated by Django 3.0.1 on 2020-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0036_auto_20200310_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(default='Four', max_length=200, null=True),
        ),
    ]
