# Generated by Django 3.0.1 on 2020-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlist', '0037_vehicle_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(default='4', max_length=200, null=True),
        ),
    ]
